- cmd/build.go
- dag/dag.go
- dag/image.go
Before these changes, when a child image failed, dib would exit silently with status code 0
> fix: Better error handling

- cmd/build.go
- dag/dag.go
- dag/image.go
- docker/builder.go
- mock/registry.go
- registry/registry.go
- types/types.go
Currently, local-only mode does not work if a subimage needs rebuild but not its parent. Dib doesn't find the version of the parent image.
This MR introduces a `retagLocal` action that will pull and tag locally the image when necessary
> fix: `Retag` when local-only is set, should pull and tag the docker image

- dag/image.go
This flag was not correctly set, and then was not correctly used when generating graphviz
> fix: Correctly set RetagDone flag

- cmd/build.go
- cmd/options.go
- cmd/test.go
- dag/dag.go
- dag/dag_test.go
- dag/image.go
- dag/image_test.go
- dgoss/dgoss.go
- dockerfile/dockerfile.go
- exec/shell.go
- graphviz/graphviz_test.go
- mock/testrunner.go
- types/types.go
Exemple of output
```
[13:16:32][INFO] Build report
[13:16:32][INFO]        [cypress-browsers-node16]: SUCCESS
[13:16:32][INFO]        [golang17-ci]: SUCCESS
[13:16:32][INFO]        [logstash-verifier]: SUCCESS
[13:16:32][INFO]        [nodejs14-cypress]: SUCCESS
[13:16:32][INFO]        [gatling]: SUCCESS
[13:16:32][INFO]        [nodejs16-playwright]: SUCCESS
[13:16:32][INFO]        [nodejs16-ci]: SUCCESS
[13:16:32][ERRO]        [nodejs12-chrome-puppeteer]: FAILURE: dgoss tests failed: failed to execute command `/bin/bash`: exit status 1
[13:16:32][INFO]        [sonar-scanner]: SUCCESS
[13:16:32][INFO]        [golang17-goreleaser]: SUCCESS
[13:16:32][INFO]        [sonar-scanner-python3.9]: SUCCESS
[13:16:32][INFO]        [sonar-scanner-php7.1]: SUCCESS
[13:16:32][INFO] …
```
> feat: Add junit dgoss reports & add human readable synthesis at build end

- .github/workflows/ci.yml
- README.md
I think the workflow that runs the checks can be renamed to `CI` as it best describes its role
> chore(ci): rename CI workflow and fix status badge URL

- dockerfile/dockerfile.go
Error was 
```
dockerfile/dockerfile.go:60:6: variable name 'd' is too short for the scope of its usage (varnamelen)
var d Dockerfile
^
```
> fix: Fix linter after golangci-lint upgrade

- cmd/build.go
- cmd/hash.go
- cmd/logger.go
- cmd/root.go
- test/fixtures/.dib-config.yml
- Moved hardcoded config for the Kaniko build backend to `viper` configuration.
- Any config can be overridden by environment variables, even when multiple levels of hierarchy :
```yaml
kaniko:
context:
s3:
bucket: "bucket-name"
```
can be overriden with `DIB_KANIKO_CONTEXT_S3_BUCKET=other-bucket`
- Kaniko backend cannot be configured with flags: this is volontary to prevent having too many flags. Might be added later if requested.
Other "normal" configuration can be done using either:
- Flag: `--registry-url`
- Env var: `DIB_REGISTRY_URL`
- File: `registry_url`
- Config keys in `yaml` file now use the `snake_case` format, instead of `kebab-case`
> feat(kaniko): source configuration from file and env

- dag/dag.go
- dag/image.go
- dag/image_test.go
- dag/report.go
Small improvement on console output to see the same kind of report we currently print for build status, but for tests.
It helps identify what went wrong with tests
```
[19:08:42][INFO] Build report
[19:08:42][INFO] 	[golang17-ci]: SUCCESS
[19:08:42][INFO] 	[golang17-goreleaser]: SUCCESS
[19:08:42][INFO] Tests report
[19:08:42][INFO] 	[golang17-ci]: PASSED
[19:08:42][INFO] 	[golang17-goreleaser]: PASSED
[19:08:42][INFO] Build process completed
```
> feat(tests): print test report

- cmd/root.go
This will avoid to have the dist directory containing the results of multiple dib runs
> feat: Cleanup dist directory before startup

- kubernetes/pod.go
When building using the kuberentes executor, if the pod gets evicted for some reason, the watcher keeps watching until we reach the timeout (1h).
This PR fixes that by adding a check on the event type, and now sends an error as soon as we detect the pod was deleted.
> fix(kubernetes): Send error when pod was unexpectedly deleted

- version/git.go
When files were renamed, git diff would only catch either the source file or the destination file. We need both to calculate dib graph
> fix: Run two git diff to catch all files renamed

- cmd/build.go
- dib/plan.go
- goss/executor_dgoss.go
- goss/executor_dgoss_test.go
- goss/executor_kubernetes.go
- version/git.go
The default shell was hardcoded, so `dib build --local-only` command failed to run tests on MacOS.
This PR will allow `dib` to autodetect the user shell from the `SHELL` environment variable
> feat(goss): detect user shell to use with docker executor

- .goreleaser.yml
- cmd/build.go
- cmd/graph.go
- cmd/logger.go
- cmd/main.go
- cmd/migrate.go
- cmd/root.go
- cmd/version.go
- main.go
Goreleaser injects the version in the `main` package by default
> fix(version): fixed package name for version injected by goreleaser

- dib/generate_dag.go
- dib/plan.go
Fix problem with different hashes being produced depending on where the docker directory is on the filesystem, or depending on which parent hash is first on the list.
> fix(hash): hash should not depend on absolute path of files

- README.md
- cmd/build.go
- cmd/root.go
- dib/build.go
- dib/build_test.go
- dib/tag.go
- dib/tag_test.go
- dockerfile/dockerfile.go
Sometimes we want to be able to build an image without using DIB (e.g. with simple `docker build` command).
This is currenlty annoying because the tag used as placeholder `DIB_MANAGED_VERSION` doesn't exist on the remote registry.
- Tag all images with the placeholder tag in release mode
- Make the placeholder tag configurable
> feat: make dib-managed dockerfiles buildable without dib

- cmd/list.go
- dib/list.go
- dib/list_test.go
- go.mod
- go.sum
- test/example_1.yml
- test/example_2.yml
- test/invalid_example.yml
This MR introduce a new "list" command that will print a list of all Docker images managed by DIB
example (with test fixtures)
```
➜ dib list 
NAME        HASH                               
bullseye    floor-venus-august-venus           
kaniko      eighteen-kitten-bakerloo-december  
multistage  cat-sweet-seven-kansas             
sub-image   whiskey-friend-happy-minnesota     
```
We can redirect output to file like these: `dib list > dib_images.yml`
We can also use a go-template to format the output like these:
```
cat template.yml
parameters:
dib_managed:
{{- range . }}
{{ .ShortName }}: {{ .Hash }}
{{- end }}
➜ dib list -o go-template-file=template.yml
parameters:
dib_managed:
bullseye: floor-venus-august-venus
kaniko: eighteen-kitten-bakerloo-december
multistage: …
```
> feat: Add "list" command to print list of images managed by DIB

- pkg/dib/build.go
- pkg/docker/builder.go
- pkg/docker/builder_test.go
- pkg/kaniko/builder.go
- pkg/kaniko/builder_test.go
- pkg/kaniko/context_remote.go
- pkg/kaniko/context_remote_test.go
- pkg/mock/builder.go
- pkg/types/types.go
I need to be able to tag an image with multiple destination tags by reusing the `github.com/radiofrance/dib/pkg/kaniko` package in a downstream application.
Both Kaniko and Docker support multiple occurrences of respectively `--destination` and `-t` flag, so I added support here and slightly changed the `ImageBuilderOpts` struct to take a slice of tags.
I also added some tests and discovered (and fixed) two small bugs:
- The kaniko builder ignores the `ImageBuilderOpts.Labels`
- The docker builder ignores the `ImageBuilderOpts.BuildArgs`
> feat(builder): support multiple destination tags

- cmd/root.go
Prevents errors when, for some commands, flag "log-level" is not set. So, in this cases, we fallback to defaultLogLevel (`info`)
```sh
$ go run ./cmd version
Invalid log level 
Error: not a valid logrus Level: ""
exit status 1
```
> fix: Fallback to default log-level if flag is not provided

- .golangci.yml
Disable deprecated linters that throw warning in logs
> chore: Update golangci-lint config after moving to v1.50.0

- cmd/build.go
- pkg/goss/executor_kubernetes.go
We loose the image name in the goss pods for now, but I'll try to put it back later, in a more generic way
> refact: Use the same code to generate pod name between goss and kaniko

- pkg/report/templates/build.go.html
- pkg/report/templates/index.go.html
- pkg/report/templates/test.go.html
- pkg/report/utils.go
Fix javascript error when image name contains dots, the `document.querySelector` call fails
> fix(report): fix html anchors not working when image name contains invalid characters

- .github/workflows/lint.golang.yml
Pin the exact version of golangci-lint to avoid breaking changes when new releases are published
> chore(ci): pin golangci-lint version

- pkg/dag/dag.go
- pkg/dag/dag_test.go
- pkg/dag/node.go
- pkg/dib/generate_dag.go
- pkg/dib/generate_dag_test.go
When nodes have more than one parent, the `dag.Walk*()` functions visit the node `n` times, with `n` the number of direct parent nodes. This behaviour is not expected and may cause bugs in the future. This change fixes that by ensuring a node can only be visited once.
> fix(dag): visit nodes only once

- cmd/root.go
Avoid cmd "docgen" to crash: https://github.com/radiofrance/dib/actions/runs/7696956248/job/20972888235#step:5:147
This command does not require any configuration file
> fix(config): No longer crashes on startup when config file doesn't exist, just warns user

- cmd/build.go
- cmd/list.go
- pkg/dib/generate_dag.go
- pkg/dib/generate_dag_test.go
- pkg/graphviz/graphviz_test.go
- test/fixtures/docker/bullseye/multistage/Dockerfile
- test/fixtures/docker/bullseye/sub-image/Dockerfile
GenerateDAG tests are now using the dockerfiles already present in the tests fixtures instead of creating new ones from scratch, and are simpler to understand.
> refactor: GenerateDAG tests

- cmd/build.go
- cmd/list.go
- docs/configuration.md
- docs/examples/config/reference.yaml
- docs/roadmap.md
- internal/logger/logger.go
- pkg/dag/image_test.go
- pkg/dib/build.go
- pkg/dib/build_test.go
- pkg/dib/generate_dag.go
- pkg/dib/generate_dag_test.go
- pkg/dib/list.go
- pkg/docker/builder.go
- pkg/dockerfile/dockerfile.go
- pkg/dockerfile/dockerfile_test.go
- pkg/exec/shell.go
- pkg/graphviz/graphviz_test.go
- pkg/kaniko/builder.go
- test/fixtures/docker/bullseye/Dockerfile
- test/fixtures/dockerfile/simple-arg.dockerfile
It is now possible to pass build-time variables with the `--build-arg` option for the `dib build` command:
```
dib build \
--build-arg FOO1="bar1" \
--build-arg FOO2=$BAR2 \
--build-arg FOO3=${BAR3}
```
Alternatively, build arguments can also be set in the `.dib.yaml` config file:
```
build_arg:
- FOO1="bar1"
- FOO2=$BAR
- FOO3=${BAR}
```
> feat: Add support for build arguments to build command

- docs/tests.md
Specify expected file ext for Goss tests
---
- Install mkdocs with python pip, then :
```
$ mkdocs serve
...
INFO    -  Documentation built in 0.43 seconds
INFO    -  [18:14:29] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [18:14:29] Serving on http://127.0.0.1:8000/
```
> chore(doc): Update tests sections

- .github/workflows/qa.yml
From [release notes of golangci-lint action v5.0.0](https://github.com/golangci/golangci-lint-action/releases/tag/v5.0.0):
> `skip-pkg-cache` and `skip-build-cache` have been removed because the cache related to Go itself is already handled by actions/setup-go.
> fix(CI): remove golangci-lint skip-pkg-cache option

- pkg/dib/generate_dag.go
- pkg/dib/generate_dag_internal_test.go
refact(GenerateDAG): split the algorithm in two parts, buildGraph and computeHashes.
The first part buildGraph needs to be unit tested, because we found some issues with its logic.
> refact(GenerateDAG): split the algorithm in two parts

- cmd/list.go
- pkg/dib/list.go
- pkg/dib/list_test.go
- pkg/graphviz/graphviz.go
- pkg/graphviz/graphviz_test.go
Give a possibility for the end user to print the actual state of the DAG using [graphviz](https://graphviz.org)
- Ensure you have `graphviz` installed : https://graphviz.org/download
- Then compile Dib locally (using GoReleaser)
```sh
make artifact
```
- And test the `dib list` command with the new option
```sh
$ ./dist/dib_linux_amd64_v1/dib list \
--config test/end2end/.dib.yaml \
--build-path test/end2end \
-o graphviz
digraph images {
rankdir = "LR";
node[fontsize=10, shape=cds, height=0.4];
edge[fontsize=10, arrowhead=vee];
"registry.localhost/base-alpine-3.19" [fillcolor=white, style=filled];
"registry.localhost/base-alpine-3.20" [fillcolor=white, style=filled];
"registry.localhost/base-debian-bookworm" [fillcolor=white, style=filled];
"registry.localhost/base-debian-bookworm" -> …
```
> feat(cli): add new output format "graphviz" for list command

- .github/workflows/docs.yml
- .github/workflows/qa.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
- .github/workflows/yaml.yml
Hi folks,
GHA now provides ARM runners for free
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> CI: ubuntu-24.04-amd64 -> ubuntu-24.04-arm

- pkg/buildkit/buildkitutil.go
- pkg/buildkit/buildkitutil_linux.go
- pkg/rootlessutil/rootless_linux.go
This pull request introduces support for rootless mode in BuildKit utilities by leveraging a new `rootlessutil` package. 
* [`pkg/buildkit/buildkitutil.go`](diffhunk://#diff-7be5906ef3f071801a35231bdbedfe635bb44e894c5a7ec2b56ae06655f74f2eL18-R23): Updated the `getHint` function to include additional instructions for rootless mode, advising the use of `rootlesskit buildkitd` when `rootlessutil.IsRootless()` is true.
* [`pkg/buildkit/buildkitutil_linux.go`](diffhunk://#diff-d07efb2e35dfd2ec6a11cc629cdfcd02922d74b90edaa0c839f70a7e3add299bR3-R10): Modified the `getRuntimeVariableDataDir` function to return the `XDGRuntimeDir` when running in rootless mode, as determined by `rootlessutil.IsRootless()`.
> Add support for rootless mode in buildkit

- pkg/buildkit/builder_darwin_test.go
- pkg/buildkit/builder_linux_test.go
- pkg/buildkit/builder_test.go
- pkg/buildkit/buildkitutil.go
- pkg/rootlessutil/rootless_linux.go
- pkg/rootlessutil/rootless_unix.go
Replaced hardcoded `unixSocketPath`  with `getBuildkitHostAddress()` in tests for greater flexibility and maintainability. Removed `runtimeVariableDataDir` and related logic as it is no longer necessary. This simplifies the code and improves readability.
> Add cross-platform rootless detection in builder test

- .github/workflows/docs.yml
- .github/workflows/qa.yml
- .github/workflows/release.yml
- .renovaterc.json
- Makefile
- cmd/docgen.go
- pkg/buildkit/buildkitutil.go
- pkg/buildkit/buildkitutil_test.go
- pkg/dib/build.go
- pkg/dib/build_test.go
- pkg/dib/generate_dag.go
- pkg/dib/generate_dag_internal_test.go
- pkg/dib/list.go
- pkg/dockerfile/dockerfile.go
- pkg/dockerfile/dockerfile_test.go
- pkg/goss/runner.go
- pkg/goss/runner_test.go
- pkg/kaniko/context_remote.go
- pkg/kaniko/context_remote_internal_test.go
- pkg/kaniko/context_remote_test.go
- pkg/kaniko/executor_kubernetes_test.go
- pkg/kaniko/s3.go
- pkg/kubernetes/exec.go
- pkg/kubernetes/pod.go
- pkg/mock/builder.go
- pkg/ratelimit/channel.go
- pkg/report/template.go
- pkg/trivy/executor_kubernetes_test.go
- pkg/trivy/runner.go
- pkg/trivy/runner_test.go
- Use golangci-lint v2.1.2 with our new .golangci.yml config file from radiofrance/lint-config v1.1.0
- Apply the needed fixes
- Improve the renovate config, so it will bump golangci-lint and radiofrance/lint-config in one PR
> maint(golangci-lint): bump to v2.1.2

- .goreleaser.yml
- Makefile
- cmd/build.go
- cmd/build_internal_test.go
- cmd/docgen.go
- cmd/list.go
- cmd/main.go
- cmd/root.go
- cmd/version.go
- main.go
The goal of this PR is to simplify and standardize the `./cmd` package, using best practices from Cobra and Viper:
- new `main.go` file at the root of the project
- files inside `./cmd` are now linked to package `cmd` instead of `main`
- sub-commands are now added in the `init` function of `rootCmd` to simplifies the command linking architecture
> refact: package `cmd`

- cmd/build.go
- pkg/buildkit/builder.go
- pkg/buildkit/builder_test.go
- pkg/buildkit/buildkitutil.go
- pkg/buildkit/context_local.go
- pkg/buildkit/context_local_test.go
- pkg/buildkit/context_remote.go
- pkg/buildkit/context_remote_test.go
- pkg/buildkit/s3.go
- pkg/dib/build.go
- pkg/dib/metadata.go
- pkg/dib/metadata_test.go
- pkg/docker/builder.go
- pkg/docker/builder_test.go
- pkg/exec/kubernetes.go
- pkg/exec/shell.go
- pkg/executor/executor.go
- pkg/goss/executor_kubernetes.go
- pkg/kaniko/builder.go
- pkg/kaniko/executor_docker.go
- pkg/kaniko/executor_docker_test.go
- pkg/kaniko/executor_kubernetes.go
- pkg/kubernetes/pod.go
- pkg/mock/executor.go
- pkg/trivy/executor_kubernetes.go
- pkg/types/types.go
This pull request introduces significant enhancements to the BuildKit backend by adding support for remote build contexts, as well as Kubernetes-based execution.
* Introduced `LocalContextProvider` and `RemoteContextProvider` to manage local and remote build contexts, respectively. Remote contexts are uploaded to storage (e.g., S3) and accessed via `pre-signed URLs` with 1 hour duration. 
* Added a Kubernetes executor (`bkKubernetesExecutor`) to run BuildKit builds in Kubernetes pods, including pod configuration, Docker config secrets, and environment variables. (`pkg/buildkit/builder.go`)
* Implemented the `buildPod` function to dynamically create Kubernetes pods for BuildKit builds, with support for custom configurations and security contexts. (`pkg/buildkit/builder.go`)
* Modified the …
> Add Kubernetes executor for Buildkit Backend

- docs/backends.md
**buildkit integration step3**
* **Added `BuildKit` as a supported build backend**: Updated the list of available backends in `docs/backends.md` to include `BuildKit`, along with its compatibility in the executor matrix.
* **Detailed `BuildKit` documentation**: Added a new section in `docs/backends.md` explaining `BuildKit`, including its features, authentication process, requirements for local and Kubernetes builds, and options for specifying a custom BuildKit host.
> docs: add BuildKit support to backends documentation

- pkg/buildkit/builder.go
default `Push` to `true` for Kubernetes executor
> feat: default push to true for Kubernetes executor 

- .goreleaser.yml
fix regression due to https://github.com/radiofrance/dib/pull/731
````
faheddorgaa@MacBook-Pro-de-fahed:~/go/src/github.com/radiofrance/dib$ ./dist/dib_darwin_amd64_v1/dib version
14:23:31  WARN   Config File ".dib" Not Found in "[/Users/faheddorgaa/.config /Users/faheddorgaa/go/src/github.com/radiofrance/dib]"
version: v0.24.1-dev
build on darwin/amd64 by goreleaser at 2025-05-14T09:28:06Z with go1.24.3 (from commit f47eede11e3e09702883abc85ca98b6dc1d06f69)
````
> fix: update ldflags to use correct package path for versioning

- README.md
- cmd/build.go
- docs/backends.md
- docs/examples/config/reference.yaml
- docs/executors.md
mark Docker and Kaniko backends as deprecated in documentation and code
> deprecate: Docker and Kaniko backends

- cmd/build.go
- pkg/buildkit/builder.go
- pkg/buildkit/builder_test.go
- pkg/buildkit/buildkitutil.go
- pkg/buildkit/buildkitutil_test.go
This PR improves BuildKit integration, refactors shell executor handling, and adds dynamic detection of BuildKit worker types.
**BuildKit Enhancements:**
- Added `GetBuildkitWorkerType` to detect worker types (`oci` or `containerd`) using `buildctl`. Updated `doBuild()` to log warnings and skip retagging for unsupported worker types.
**Shell Executor Refactor:**
- `NewBKBuilder` now accepts a `ShellExecutor` as a parameter for better flexibility and testability. Replaced inline `ShellExecutor` creation with `exec.NewShellExecutor`.
**Unit Tests:**
- Added tests for `GetBuildkitWorkerType` to handle various scenarios (e.g., invalid JSON, missing labels).
> fix: prevent image retagging with BuildKit backend && some refacto

- README.md
- cmd/root.go
- examples/README.md
update references from Docker Image Builder to DAG Image Builder in documentation
> rename: [docker images builder] -> [DAG image builder]

- cmd/build.go
- cmd/docgen.go
- cmd/list.go
- cmd/root.go
* Add the `SilenceUsage: true` flag to all command definitions.
This flag prevents Cobra from automatically displaying the command's usage information when an error occurs, resulting in cleaner error output.
* Remove the duplicate error message produced by the program's logging module and Cobra's stderr.
> feat: enable silent usage for CLI commands
